// =====================================================================
// === tests/pedidos-schema.smoke.js ====================================
// Smoke estático para a migration db/13_pedidos_schema.sql.
//
// Fase: RAVATEX-TAPETES-PEDIDOS-SCHEMA-RLS-A
// Escopo: valida que o SQL versionado está correto e pronto para ser
// aplicado em staging em fase posterior. Não executa o SQL.
//
// Verifica (sem aplicar no Supabase):
//   - arquivo SQL novo existe e menciona a fase;
//   - cria tabela public.pedidos com schema correto;
//   - cria tabela public.pedido_itens com schema correto;
//   - cria tabela public.pedido_eventos com schema correto;
//   - adiciona `lotes.pedido_id` (nullable, FK para pedidos);
//   - NÃO cria `pedidos.op_id`;
//   - status contém os 6 valores esperados;
//   - `numero` tem geração automática (GENERATED BY DEFAULT AS IDENTITY);
//   - RLS habilitada nas 3 novas tabelas;
//   - policies admin-only em todas as 3;
//   - sem policy para anon;
//   - sem policy pública por token;
//   - idempotente (IF NOT EXISTS / DROP IF EXISTS);
//   - sem DELETE FROM / DROP TABLE destrutivo;
//   - sem secrets, JWT, service_role, password literal longo;
//   - não altera db/01-12;
//   - não toca js/ ou supabase/functions/.
// =====================================================================

const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const ROOT = path.resolve(__dirname, "..");
const SQL = path.join(ROOT, "db", "13_pedidos_schema.sql");
const SCHEMA_01 = path.join(ROOT, "db", "01_schema.sql");
const FASE_06 = path.join(ROOT, "db", "09_fase6_cliente_lote.sql");
const FASE_12 = path.join(ROOT, "db", "12_auth_user_disable_schema.sql");
const ADMIN_CREATE_USER = path.join(
  ROOT, "supabase", "functions", "admin-create-user", "index.ts"
);

function readOrFail(p) {
  assert.ok(fs.existsSync(p), "arquivo não encontrado: " + p);
  return fs.readFileSync(p, "utf8");
}

const sql = readOrFail(SQL);
const schema01 = readOrFail(SCHEMA_01);
const fase06 = readOrFail(FASE_06);
const fase12 = readOrFail(FASE_12);
const adminCreateUserSrc = fs.existsSync(ADMIN_CREATE_USER)
  ? fs.readFileSync(ADMIN_CREATE_USER, "utf8")
  : "";

// ---------------------------------------------------------------------
// 1. Existência e estrutura básica
// ---------------------------------------------------------------------

test("arquivo db/13_pedidos_schema.sql existe", () => {
  assert.ok(fs.existsSync(SQL), "db/13_pedidos_schema.sql ausente");
});

test("SQL: tem header com nome da fase", () => {
  assert.match(
    sql,
    /RAVATEX-TAPETES-PEDIDOS-SCHEMA-RLS-A/,
    "header deve mencionar a fase RAVATEX-TAPETES-PEDIDOS-SCHEMA-RLS-A"
  );
});

test("SQL: documenta design e decisões de contrato", () => {
  assert.match(sql, /Product Contract/i);
  assert.match(sql, /Pedido \u00e9 entidade comercial separada de OP/i);
  assert.match(sql, /lotes\.pedido_id/i);
});

// ---------------------------------------------------------------------
// 2. Tabela public.pedidos
// ---------------------------------------------------------------------

test("SQL: cria tabela public.pedidos", () => {
  assert.match(
    sql,
    /CREATE\s+TABLE\s+IF\s+NOT\s+EXISTS\s+public\.pedidos/i,
    "deve criar tabela public.pedidos com IF NOT EXISTS"
  );
});

test("SQL: pedidos tem id UUID PK com gen_random_uuid", () => {
  assert.match(
    sql,
    /id\s+UUID\s+PRIMARY\s+KEY\s+DEFAULT\s+gen_random_uuid\(\)/i,
    "id deve ser UUID PRIMARY KEY DEFAULT gen_random_uuid()"
  );
});

test("SQL: pedidos tem cliente_id BIGINT FK para clientes", () => {
  assert.match(
    sql,
    /cliente_id\s+BIGINT\s+NOT\s+NULL\s+REFERENCES\s+public\.clientes/i,
    "cliente_id deve ser BIGINT NOT NULL FK para public.clientes"
  );
});

test("SQL: pedidos.numero tem geração automática", () => {
  assert.match(
    sql,
    /numero\s+BIGINT\s+GENERATED\s+BY\s+DEFAULT\s+AS\s+IDENTITY\s+UNIQUE/i,
    "numero deve ser BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE"
  );
});

test("SQL: pedidos.status tem CHECK com 6 valores", () => {
  assert.match(
    sql,
    /status\s+TEXT\s+NOT\s+NULL\s+DEFAULT\s+'rascunho'/i,
    "status deve ter DEFAULT 'rascunho'"
  );
  for (const code of [
    "'rascunho'",
    "'recebido'",
    "'confirmado'",
    "'produzindo'",
    "'entregue'",
    "'cancelado'",
  ]) {
    assert.match(
      sql,
      new RegExp(code),
      "status CHECK deve conter " + code
    );
  }
});

test("SQL: pedidos tem prazo_entrega DATE NULL", () => {
  assert.match(
    sql,
    /prazo_entrega\s+DATE/i,
    "prazo_entrega deve ser DATE"
  );
});

test("SQL: pedidos tem token_acesso UUID UNIQUE", () => {
  assert.match(
    sql,
    /token_acesso\s+UUID\s+UNIQUE\s+DEFAULT\s+gen_random_uuid\(\)/i,
    "token_acesso deve ser UUID UNIQUE DEFAULT gen_random_uuid()"
  );
});

test("SQL: pedidos tem criado_em e atualizado_em TIMESTAMPTZ", () => {
  assert.match(sql, /criado_em\s+TIMESTAMPTZ\s+NOT\s+NULL\s+DEFAULT\s+now\(\)/i);
  assert.match(sql, /atualizado_em\s+TIMESTAMPTZ\s+NOT\s+NULL\s+DEFAULT\s+now\(\)/i);
});

// ---------------------------------------------------------------------
// 3. Tabela public.pedido_itens
// ---------------------------------------------------------------------

test("SQL: cria tabela public.pedido_itens", () => {
  assert.match(
    sql,
    /CREATE\s+TABLE\s+IF\s+NOT\s+EXISTS\s+public\.pedido_itens/i,
    "deve criar tabela public.pedido_itens"
  );
});

test("SQL: pedido_itens.pedido_id FK CASCADE", () => {
  assert.match(
    sql,
    /pedido_id\s+UUID\s+NOT\s+NULL\s+REFERENCES\s+public\.pedidos\(id\)\s+ON\s+DELETE\s+CASCADE/i,
    "pedido_id deve ter ON DELETE CASCADE"
  );
});

test("SQL: pedido_itens.modelo_id BIGINT FK para modelos", () => {
  assert.match(
    sql,
    /modelo_id\s+BIGINT\s+NOT\s+NULL\s+REFERENCES\s+public\.modelos/i,
    "modelo_id deve ser BIGINT NOT NULL FK para public.modelos"
  );
});

test("SQL: pedido_itens.metros NUMERIC > 0", () => {
  assert.match(
    sql,
    /metros\s+NUMERIC\(10,2\)\s+NOT\s+NULL\s+CHECK\s*\(metros\s*>\s*0\)/i,
    "metros deve ser NUMERIC(10,2) NOT NULL CHECK > 0"
  );
});

test("SQL: pedido_itens.largura e cores são nullable (overrides)", () => {
  assert.match(
    sql,
    /largura\s+NUMERIC\(3,2\)\s+CHECK\s*\(largura\s+IS\s+NULL\s+OR\s+largura\s+IN\s+\(1\.40,\s*2\.10\)\)/i,
    "largura deve permitir NULL com CHECK restrito"
  );
  assert.match(
    sql,
    /cor_1_id\s+BIGINT\s+REFERENCES\s+public\.cores/i,
    "cor_1_id deve ser FK nullable para cores"
  );
  assert.match(
    sql,
    /cor_2_id\s+BIGINT\s+REFERENCES\s+public\.cores/i,
    "cor_2_id deve ser FK nullable para cores"
  );
});

// ---------------------------------------------------------------------
// 4. Tabela public.pedido_eventos
// ---------------------------------------------------------------------

test("SQL: cria tabela public.pedido_eventos", () => {
  assert.match(
    sql,
    /CREATE\s+TABLE\s+IF\s+NOT\s+EXISTS\s+public\.pedido_eventos/i,
    "deve criar tabela public.pedido_eventos"
  );
});

test("SQL: pedido_eventos.pedido_id FK CASCADE", () => {
  assert.match(
    sql,
    /pedido_id\s+UUID\s+NOT\s+NULL\s+REFERENCES\s+public\.pedidos\(id\)\s+ON\s+DELETE\s+CASCADE/i,
    "pedido_id em pedido_eventos deve ter ON DELETE CASCADE"
  );
});

test("SQL: pedido_eventos.criado_por FK para auth.users", () => {
  assert.match(
    sql,
    /criado_por\s+UUID\s+REFERENCES\s+auth\.users/i,
    "criado_por deve ser FK para auth.users"
  );
});

// ---------------------------------------------------------------------
// 5. Vínculo Lote → Pedido (nullable)
// ---------------------------------------------------------------------

test("SQL: adiciona lotes.pedido_id UUID NULLABLE", () => {
  assert.match(
    sql,
    /ALTER\s+TABLE\s+public\.lotes\s+ADD\s+COLUMN\s+IF\s+NOT\s+EXISTS\s+pedido_id\s+UUID\s+REFERENCES\s+public\.pedidos/i,
    "deve adicionar lotes.pedido_id UUID FK para pedidos"
  );
});

test("SQL: lotes.pedido_id tem ON DELETE SET NULL (não cascata OPs)", () => {
  assert.match(
    sql,
    /pedido_id\s+UUID\s+REFERENCES\s+public\.pedidos\(id\)\s+ON\s+DELETE\s+SET\s+NULL/i,
    "lotes.pedido_id deve ter ON DELETE SET NULL"
  );
});

// ---------------------------------------------------------------------
// 6. NUNCA criar pedidos.op_id
// ---------------------------------------------------------------------

test("SQL: NÃO cria coluna pedidos.op_id", () => {
  // Verifica que `op_id` não aparece como coluna em public.pedidos.
  // Comentários podem mencionar. O foco é: nenhum `op_id` como coluna.
  // Procura por padrões SQL reais: `op_id TIPO` (definição de coluna).
  assert.doesNotMatch(
    sql,
    /op_id\s+(BIGINT|INTEGER|INT|UUID|TEXT|NUMERIC|BIGSERIAL|SMALLINT|CHAR|VARCHAR)/i,
    "nenhuma coluna op_id deve ser definida (op_id TIPO)"
  );
  // Verifica também que o bloco da tabela pedidos não tem op_id.
  const pedidosTableMatch = sql.match(
    /CREATE\s+TABLE\s+IF\s+NOT\s+EXISTS\s+public\.pedidos[\s\S]*?(?=\n\s*CREATE\s+TABLE|\n\s*ALTER\s+TABLE|\n\s*COMMENT\s+ON\s+TABLE|\n\s*--\s*===)/i
  );
  if (pedidosTableMatch) {
    const pedidosBlock = pedidosTableMatch[0];
    assert.doesNotMatch(
      pedidosBlock,
      /\bop_id\b/i,
      "bloco CREATE TABLE public.pedidos não deve conter op_id"
    );
  }
});

// ---------------------------------------------------------------------
// 7. Índices
// ---------------------------------------------------------------------

test("SQL: cria índices esperados", () => {
  for (const idx of [
    /pedidos_cliente_idx/i,
    /pedidos_status_idx/i,
    /pedidos_token_idx/i,
    /pedido_itens_pedido_idx/i,
    /pedido_eventos_pedido_idx/i,
    /lotes_pedido_idx/i,
  ]) {
    assert.match(sql, idx, "deve criar índice " + idx.source);
  }
});

// ---------------------------------------------------------------------
// 8. RLS — habilitada e admin-only
// ---------------------------------------------------------------------

test("SQL: habilita RLS nas 3 novas tabelas", () => {
  for (const tbl of [
    /ALTER\s+TABLE\s+public\.pedidos\s+ENABLE\s+ROW\s+LEVEL\s+SECURITY/i,
    /ALTER\s+TABLE\s+public\.pedido_itens\s+ENABLE\s+ROW\s+LEVEL\s+SECURITY/i,
    /ALTER\s+TABLE\s+public\.pedido_eventos\s+ENABLE\s+ROW\s+LEVEL\s+SECURITY/i,
  ]) {
    assert.match(sql, tbl, "deve habilitar RLS em " + tbl.source);
  }
});

test("SQL: cria policy admin-only em cada tabela nova", () => {
  assert.match(sql, /pedidos_admin_all[\s\S]{0,500}?FOR\s+ALL/i,
    "deve ter policy pedidos_admin_all FOR ALL");
  assert.match(sql, /pedido_itens_admin_all[\s\S]{0,500}?FOR\s+ALL/i,
    "deve ter policy pedido_itens_admin_all FOR ALL");
  assert.match(sql, /pedido_eventos_admin_all[\s\S]{0,500}?FOR\s+ALL/i,
    "deve ter policy pedido_eventos_admin_all FOR ALL");
  // Todas devem usar is_admin()
  for (const p of [/pedidos_admin_all/i, /pedido_itens_admin_all/i, /pedido_eventos_admin_all/i]) {
    const idx = sql.search(p);
    assert.ok(idx > 0, "policy " + p.source + " deve existir");
    const bloco = sql.slice(idx, idx + 600);
    assert.match(bloco, /is_admin\(\)/i, "policy " + p.source + " deve usar is_admin()");
  }
});

// ---------------------------------------------------------------------
// 9. Sem policy pública / sem token público nesta fase
// ---------------------------------------------------------------------

test("SQL: NÃO cria policy pública para anon", () => {
  assert.doesNotMatch(
    sql,
    /FOR\s+SELECT[\s\S]{0,300}TO\s+anon/i,
    "não deve criar policy SELECT TO anon (admin-only)"
  );
});

test("SQL: NÃO cria policy para authenticated genérica", () => {
  assert.doesNotMatch(
    sql,
    /FOR\s+ALL[\s\S]{0,300}TO\s+authenticated[\s\S]{0,300}USING\s*\(\s*true\s*\)/i,
    "não deve criar policy FOR ALL TO authenticated USING(true)"
  );
});

test("SQL: NÃO usa token_acesso em nenhuma USING clause", () => {
  // Confirma que token_acesso não é exposto via RLS direta.
  // Comentários podem mencionar; o que importa é não usar em USING/WITH CHECK.
  assert.doesNotMatch(
    sql,
    /USING\s*\(\s*token_acesso/i,
    "token_acesso não pode aparecer em USING (sem policy pública)"
  );
  assert.doesNotMatch(
    sql,
    /WITH\s+CHECK\s*\(\s*token_acesso/i,
    "token_acesso não pode aparecer em WITH CHECK"
  );
});

// ---------------------------------------------------------------------
// 10. Idempotência e segurança
// ---------------------------------------------------------------------

test("SQL: é idempotente (IF NOT EXISTS em CREATE TABLE/INDEX, ADD COLUMN IF NOT EXISTS)", () => {
  assert.match(sql, /CREATE\s+TABLE\s+IF\s+NOT\s+EXISTS\s+public\.pedidos/i);
  assert.match(sql, /CREATE\s+TABLE\s+IF\s+NOT\s+EXISTS\s+public\.pedido_itens/i);
  assert.match(sql, /CREATE\s+TABLE\s+IF\s+NOT\s+EXISTS\s+public\.pedido_eventos/i);
  assert.match(sql, /ADD\s+COLUMN\s+IF\s+NOT\s+EXISTS\s+pedido_id/i);
  assert.match(sql, /CREATE\s+INDEX\s+IF\s+NOT\s+EXISTS\s+pedidos_cliente_idx/i);
});

test("SQL: não contém DELETE FROM / TRUNCATE / DROP TABLE destrutivo", () => {
  assert.doesNotMatch(sql, /DELETE\s+FROM/i, "não deve ter DELETE FROM");
  assert.doesNotMatch(sql, /TRUNCATE/i, "não deve ter TRUNCATE");
  assert.doesNotMatch(sql, /DROP\s+TABLE/i, "não deve ter DROP TABLE destrutivo");
  // DROP POLICY IF EXISTS é OK (idempotente).
  assert.match(sql, /DROP\s+POLICY\s+IF\s+EXISTS/i, "DROP POLICY IF EXISTS é OK (idempotente)");
});

test("SQL: não contém service_role / SUPABASE_SERVICE_ROLE_KEY / JWT hardcoded", () => {
  assert.doesNotMatch(sql, /service_role/i);
  assert.doesNotMatch(sql, /SUPABASE_SERVICE_ROLE_KEY/i);
  assert.doesNotMatch(sql, /eyJ[A-Za-z0-9_-]{10,}\.eyJ[A-Za-z0-9_-]{10,}\./);
});

test("SQL: não contém password literal longo", () => {
  assert.doesNotMatch(
    sql,
    /password\s*[:=]\s*['"][A-Za-z0-9._-]{20,}['"]/i
  );
});

test("SQL: termina com reload do schema cache (PostgREST)", () => {
  assert.match(sql, /NOTIFY\s+pgrst,\s*'reload\s+schema'/i);
  assert.match(sql, /NOTIFY\s+pgrst,\s*'reload\s+config'/i);
});

// ---------------------------------------------------------------------
// 11. Não toca migrations antigas / código / Edge Functions
// ---------------------------------------------------------------------

test("SQL: não referencia migrations antigas (db/01-12) para alteração", () => {
  // Comentários podem mencionar; o que importa é não haver DROP/ALTER de
  // tabelas de outras migrations além de `lotes` (que está na mig 09).
  assert.doesNotMatch(
    sql,
    /DROP\s+TABLE\s+(public\.)?(usuarios|clientes|cores|modelos|fornecedores|ops|op_itens|op_fornecedores|entregas|entrega_itens|ordens_compra_fio|saldo_fios)/i,
    "não deve dropar tabelas de outras migrations"
  );
});

test("SQL: não altera fluxo de OP (não toca ops, op_itens, op_fornecedores)", () => {
  assert.doesNotMatch(
    sql,
    /ALTER\s+TABLE\s+public\.ops[^;]*\b(?!ADD\s+COLUMN)/i,
    "não deve alterar tabela ops além do já feito em db/09"
  );
  assert.doesNotMatch(sql, /ALTER\s+TABLE\s+public\.op_itens/i,
    "não deve alterar op_itens");
  assert.doesNotMatch(sql, /ALTER\s+TABLE\s+public\.op_fornecedores/i,
    "não deve alterar op_fornecedores");
});

test("SQL: não toca js/ ou supabase/functions/", () => {
  // Nenhum caminho para js/ ou supabase/functions/.
  assert.doesNotMatch(sql, /js\//i, "não deve referenciar js/");
  assert.doesNotMatch(sql, /supabase\/functions\//i, "não deve referenciar supabase/functions/");
  assert.doesNotMatch(sql, /admin-create-user/i, "não deve referenciar admin-create-user");
  assert.doesNotMatch(sql, /admin-disable-user/i, "não deve referenciar admin-disable-user");
  assert.doesNotMatch(sql, /admin-delete-user/i, "não deve referenciar admin-delete-user");
});

// ---------------------------------------------------------------------
// 12. Não conflita com migrations existentes
// ---------------------------------------------------------------------

test("schema 01 não tem tabelas pedidos/pedido_itens/pedido_eventos", () => {
  assert.doesNotMatch(schema01, /CREATE\s+TABLE[^;]*public\.pedidos/i);
  assert.doesNotMatch(schema01, /CREATE\s+TABLE[^;]*public\.pedido_itens/i);
  assert.doesNotMatch(schema01, /CREATE\s+TABLE[^;]*public\.pedido_eventos/i);
});

test("fase 06 (cliente/lote) não tem pedidos nem lotes.pedido_id", () => {
  // Usa word boundary para evitar match em "metros_pedidos" (que existe em op_itens).
  assert.doesNotMatch(fase06, /\bpedidos\b/i);
  assert.doesNotMatch(fase06, /lotes\.pedido_id/i);
});

test("fase 12 (auth user disable) não tem pedidos", () => {
  assert.doesNotMatch(fase12, /pedidos/i);
});

// ---------------------------------------------------------------------
// 13. Não inventa trigger complexo (criado no MVP, sem automação)
// ---------------------------------------------------------------------

test("SQL: não cria trigger complexo de evento automático", () => {
  // O MVP cria a tabela pedido_eventos mas não cria trigger que popule
  // automaticamente. Trigger de auditoria pode vir em fase futura.
  assert.doesNotMatch(
    sql,
    /CREATE\s+(?:OR\s+REPLACE\s+)?FUNCTION[^;]*pedido_evento/i,
    "não deve criar trigger/function automática de pedido_eventos no MVP"
  );
  assert.doesNotMatch(
    sql,
    /CREATE\s+TRIGGER[\s\S]{0,200}pedido/i,
    "não deve criar trigger sobre pedidos no MVP"
  );
});

// ---------------------------------------------------------------------
// 14. Sanidade: admin-create-user continua igual (não foi alterado por esta fase)
// ---------------------------------------------------------------------

test("admin-create-user/index.ts: não foi alterado por esta fase", () => {
  if (!adminCreateUserSrc) return; // não existe
  assert.match(
    adminCreateUserSrc,
    /admin-create-user:.*[Vv]ari[áa]veis de ambiente/,
    "header esperado continua presente em admin-create-user"
  );
});
