-- ============================================================
-- Fase: RAVATEX-TAPETES-PEDIDOS-SCHEMA-RLS-A
-- Pedidos do cliente — schema/RLS versionado no repositório.
--
-- Design:
--   Product Contract Consolidado v1 (RAVATEX-TAPETES-PEDIDOS-CLIENTE-PRODUCT-CONTRACT-R1)
--
-- Compatibilidade com schema atual:
--   - clientes.id existe (db/09_fase6_cliente_lote.sql) → BIGSERIAL.
--   - modelos.id existe (db/01_schema.sql) → BIGSERIAL.
--   - cores.id existe (db/01_schema.sql) → BIGSERIAL.
--   - lotes.id existe (db/09_fase6_cliente_lote.sql) → BIGSERIAL.
--   - is_admin() já recriada para exigir `ativo IS TRUE` (db/12_*).
--
-- Decisões de design aplicadas:
--   - Pedido é entidade comercial separada de OP.
--   - OP pode existir sem Pedido (produção avulsa).
--   - Pedido pode gerar zero, uma ou várias OPs.
--   - Vínculo Pedido → Lote → OP(s) via `lotes.pedido_id` (nullable).
--   - Não criar `pedidos.op_id` (nunca).
--   - `largura`/`cor_1_id`/`cor_2_id` em `pedido_itens` são NULLABLE:
--     se NULL, usar dados do modelo. MVP não usa override.
--   - Status do MVP admin: 'rascunho','recebido','confirmado','cancelado'.
--     'produzindo' e 'entregue' ficam disponíveis para fases futuras.
--   - Token público NÃO é exposto nesta fase (sem policy pública).
--
-- Não implementado nesta fase:
--   - Telas admin de Pedido.
--   - Telas cliente (token ou login).
--   - Geração automática de OP a partir de Pedido.
--   - Trigger de evento em mudança de status (criado no MVP, sem trigger).
--
-- Idempotente: pode rodar várias vezes sem efeito cumulativo.
-- Sem DELETE destrutivo, sem dados reais, sem secrets.
-- Sem alterar migrations antigas, sem tocar frontend, sem tocar Edge Functions.
-- ============================================================


-- ============================================================
-- 1. Tabela public.pedidos
-- ============================================================

CREATE TABLE IF NOT EXISTS public.pedidos (
  id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  cliente_id      BIGINT      NOT NULL REFERENCES public.clientes(id) ON DELETE RESTRICT,
  -- numero sequencial global por projeto, idempotente e único.
  -- Usa GENERATED BY DEFAULT para permitir override manual se necessário.
  numero          BIGINT      GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  status          TEXT        NOT NULL DEFAULT 'rascunho'
                  CHECK (status IN ('rascunho','recebido','confirmado','produzindo','entregue','cancelado')),
  prazo_entrega   DATE,
  observacao      TEXT,
  -- Token de acesso público (preparado para fase futura com Edge Function sanitizada).
  -- Nesta fase NÃO há policy pública; RLS fica admin-only.
  token_acesso    UUID        UNIQUE DEFAULT gen_random_uuid(),
  criado_em       TIMESTAMPTZ NOT NULL DEFAULT now(),
  atualizado_em   TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.pedidos IS 'Pedido comercial do cliente (entidade separada de OP).';
COMMENT ON COLUMN public.pedidos.status IS 'rascunho|recebido|confirmado|produzindo|entregue|cancelado';
COMMENT ON COLUMN public.pedidos.token_acesso IS 'Token para consulta pública futura via Edge Function. Não usado no MVP.';


-- ============================================================
-- 2. Tabela public.pedido_itens
-- ============================================================

CREATE TABLE IF NOT EXISTS public.pedido_itens (
  id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  pedido_id       UUID        NOT NULL REFERENCES public.pedidos(id) ON DELETE CASCADE,
  modelo_id       BIGINT      NOT NULL REFERENCES public.modelos(id) ON DELETE RESTRICT,
  metros          NUMERIC(10,2) NOT NULL CHECK (metros > 0),
  -- Overrides opcionais para o modelo. Se NULL, a UI usa dados do modelo.
  largura         NUMERIC(3,2) CHECK (largura IS NULL OR largura IN (1.40, 2.10)),
  cor_1_id        BIGINT      REFERENCES public.cores(id) ON DELETE RESTRICT,
  cor_2_id        BIGINT      REFERENCES public.cores(id) ON DELETE RESTRICT,
  observacao      TEXT,
  ordem           INTEGER     NOT NULL DEFAULT 0,
  criado_em       TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.pedido_itens IS 'Itens do pedido. No MVP, usa modelo_id + metros; largura e cores vêm do modelo.';
COMMENT ON COLUMN public.pedido_itens.largura IS 'Override opcional do modelo. Se NULL, usar modelo.largura.';
COMMENT ON COLUMN public.pedido_itens.cor_1_id IS 'Override opcional. Se NULL, usar modelo.cor_1_id.';
COMMENT ON COLUMN public.pedido_itens.cor_2_id IS 'Override opcional. Se NULL, usar modelo.cor_2_id.';


-- ============================================================
-- 3. Tabela public.pedido_eventos (auditoria opcional)
-- ============================================================

CREATE TABLE IF NOT EXISTS public.pedido_eventos (
  id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  pedido_id       UUID        NOT NULL REFERENCES public.pedidos(id) ON DELETE CASCADE,
  status_anterior TEXT,
  status_novo     TEXT        NOT NULL,
  criado_por      UUID        REFERENCES auth.users(id) ON DELETE SET NULL,
  criado_em       TIMESTAMPTZ NOT NULL DEFAULT now(),
  observacao      TEXT
);

COMMENT ON TABLE public.pedido_eventos IS 'Eventos de auditoria do pedido. MVP: opcional. Trigger de evento será decidido em fase futura.';


-- ============================================================
-- 4. Vínculo Lote → Pedido (nullable)
--    Lote pode existir sem Pedido (produção avulsa).
--    Pedido pode existir sem Lote (rascunho antes de programar).
-- ============================================================

ALTER TABLE public.lotes
  ADD COLUMN IF NOT EXISTS pedido_id UUID REFERENCES public.pedidos(id) ON DELETE SET NULL;

COMMENT ON COLUMN public.lotes.pedido_id IS 'Pedido comercial que originou este lote. NULL se lote existe sem pedido.';


-- ============================================================
-- 5. Índices
-- ============================================================

CREATE INDEX IF NOT EXISTS pedidos_cliente_idx       ON public.pedidos(cliente_id);
CREATE INDEX IF NOT EXISTS pedidos_status_idx         ON public.pedidos(status);
CREATE INDEX IF NOT EXISTS pedidos_token_idx          ON public.pedidos(token_acesso);
CREATE INDEX IF NOT EXISTS pedido_itens_pedido_idx    ON public.pedido_itens(pedido_id);
CREATE INDEX IF NOT EXISTS pedido_eventos_pedido_idx  ON public.pedido_eventos(pedido_id, criado_em DESC);
CREATE INDEX IF NOT EXISTS lotes_pedido_idx          ON public.lotes(pedido_id);


-- ============================================================
-- 6. RLS — admin-only em todas as 3 novas tabelas
-- ============================================================

-- 6.1 pedidos
ALTER TABLE public.pedidos ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS pedidos_admin_all ON public.pedidos;
CREATE POLICY pedidos_admin_all ON public.pedidos
  FOR ALL
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

-- 6.2 pedido_itens
ALTER TABLE public.pedido_itens ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS pedido_itens_admin_all ON public.pedido_itens;
CREATE POLICY pedido_itens_admin_all ON public.pedido_itens
  FOR ALL
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

-- 6.3 pedido_eventos
ALTER TABLE public.pedido_eventos ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS pedido_eventos_admin_all ON public.pedido_eventos;
CREATE POLICY pedido_eventos_admin_all ON public.pedido_eventos
  FOR ALL
  USING (public.is_admin())
  WITH CHECK (public.is_admin());


-- ============================================================
-- 7. Comentários sobre semântica
-- ============================================================
-- - Pedido é independente de OP. Um Pedido pode gerar zero, uma ou várias OPs.
--   Uma OP pode existir sem Pedido.
-- - O vínculo é via `lotes.pedido_id` (nullable). NUNCA via `pedidos.op_id`.
-- - `lotes.pedido_id` ON DELETE SET NULL: apagar pedido não cascateia OPs.
-- - `pedido_itens.pedido_id` ON DELETE CASCADE: apagar pedido apaga os itens.
-- - RLS é estritamente admin-only nesta fase. Política pública (por token) só
--   em fase futura via Edge Function sanitizada (NÃO via RLS direta).
-- - Sem trigger automático de `pedido_eventos` no MVP. Eventos podem ser
--   inseridos manualmente pela UI ou RPC futura.
-- ============================================================


-- ============================================================
-- 8. Reload do schema cache (PostgREST)
-- ============================================================
NOTIFY pgrst, 'reload schema';
NOTIFY pgrst, 'reload config';
