-- =====================================================================
-- db/89_pedido_commercial_date_and_number_control.sql
-- KLEBER-APP-OPERATIONAL-STABILIZATION-BATCH-02-R1 — commercial Pedido
-- date and controlled Pedido numbering.
--
-- Order: KLEBER-APP-OPERATIONAL-STABILIZATION-BATCH-02-R1.
-- Schema shapes: docs/architecture/PEDIDO_OP_SCHEMA_CONTRACT.md.
-- Forward-only; db/01..db/88 are untouched. The migration terminal guard
-- advances 88 -> 89 in the same commit (tests/ordem-compra-c3d-deploy.smoke.js).
--
-- WHAT THIS MIGRATION OWNS
--   A. public.pedidos.data_pedido — the COMMERCIAL order date. It is a
--      business fact the operator states and may correct; it is NOT the
--      technical creation instant. `criado_em` remains the immutable
--      technical timestamp and must never again be read as the commercial
--      date. Existing rows are backfilled from `criado_em` projected onto
--      the Brazil business calendar, which is the only interpretation that
--      reproduces the date the operator actually saw when the row was made.
--
--      NOTE ON THE HOMONYM: public.ordens_compra_fio.data_pedido already
--      exists (db/01) and means "yarn purchase-order date". Column names are
--      table-scoped and the architect ruled explicitly that this is not a
--      collision. Neither column references the other.
--
--   B. public.pedidos.numero — the sequential commercial identity. It stays
--      GENERATED BY DEFAULT AS IDENTITY with its UNIQUE constraint, so an
--      operator may state a number explicitly at creation. This migration
--      adds the three controls that identity alone does not give:
--        1. positivity  — numero > 0;
--        2. immutability — no path may renumber an existing Pedido;
--        3. sequence synchronization — an explicit HIGH number advances the
--           identity sequence so a later automatic number cannot collide
--           with it.
--
-- WHY THE SEQUENCE MUST BE SYNCHRONIZED
--   `GENERATED BY DEFAULT AS IDENTITY` lets an INSERT supply its own value
--   WITHOUT consuming the sequence. So an operator creating Pedido 5000 by
--   hand leaves the sequence at, say, 41; automatic numbering then walks
--   42, 43, ... and eventually reaches 5000 and fails on UNIQUE(numero) —
--   a failure surfacing years later, to a different user, with no relation
--   to its cause. Synchronizing forward at insert time converts that latent
--   collision into a gap, which is explicitly acceptable.
--
-- NUMBERING GUARANTEES (and non-guarantees)
--   * The sequence NEVER moves backwards: an explicit LOW unused number
--     leaves it untouched.
--   * Numbering is increasing, not gapless. Gaps from rollback, compensation
--     or an explicit high number are accepted by design; gapless numbering is
--     NOT attempted and would require serializing every Pedido creation.
--   * UNIQUE(numero) remains the final concurrency backstop: two concurrent
--     inserts of the SAME explicit number produce exactly one Pedido, and the
--     loser gets 23505 regardless of any advisory lock.
--
-- LOCK ORDER
--   The synchronizer takes pg_advisory_xact_lock FIRST and touches no table
--   row, so it introduces no new edge into the global lock order established
--   by db/88. It is a LEAF.
--
-- No RLS policy, grant, existing constraint, existing trigger, existing RPC
-- or Manta/OP/expedition behavior is changed. No data is repaired or
-- reinterpreted beyond the declared data_pedido backfill.
--
-- Idempotente: pode rodar varias vezes sem efeito cumulativo e sem drift.
-- Depende de db/13.
-- Aplicar SOMENTE em ambiente local/descartavel. NAO aplicar em shared
-- development, staging ou producao sem ordem explicita.
-- =====================================================================

BEGIN;

-- ============================================================
-- 0. PRE-EXISTING DATA GATE.
--    Fail closed if any existing Pedido already violates what this
--    migration makes authoritative. No repair, no reinterpretation.
-- ============================================================
DO $gate$
DECLARE
  v_bad_count INTEGER;
  v_bad_ids   UUID[];
BEGIN
  SELECT count(*), array_agg(id ORDER BY id)
    INTO v_bad_count, v_bad_ids
    FROM public.pedidos
   WHERE numero IS NULL OR numero <= 0;

  IF v_bad_count > 0 THEN
    RAISE EXCEPTION
      'db/89 gate: % pedido(s) com numero nulo ou nao positivo; corrija sob ordem propria antes de aplicar. ids=%',
      v_bad_count, v_bad_ids;
  END IF;
END;
$gate$;

-- ============================================================
-- 1. public.pedidos.data_pedido — data comercial do Pedido
--    Sequencia exigida: coluna nullable -> backfill -> default -> NOT NULL.
--    Cada passo e idempotente.
-- ============================================================

-- 1.1 coluna nullable
ALTER TABLE public.pedidos
  ADD COLUMN IF NOT EXISTS data_pedido DATE;

-- 1.2 backfill das linhas existentes a partir de criado_em, projetado no
--     calendario comercial do Brasil. Toca APENAS linhas ainda nulas, entao
--     um replay nunca reescreve uma data ja corrigida pelo operador.
UPDATE public.pedidos
   SET data_pedido = (criado_em AT TIME ZONE 'America/Sao_Paulo')::date
 WHERE data_pedido IS NULL;

-- 1.3 default = data local do Brasil no momento da insercao.
--     now() e TIMESTAMPTZ; AT TIME ZONE projeta no fuso comercial antes do
--     ::date, entao um Pedido criado as 22h de Sao Paulo nao recebe a data
--     do dia seguinte (que e o que CURRENT_DATE em UTC produziria).
ALTER TABLE public.pedidos
  ALTER COLUMN data_pedido SET DEFAULT (now() AT TIME ZONE 'America/Sao_Paulo')::date;

-- 1.4 NOT NULL (o backfill acima garante que nao ha nulo remanescente)
ALTER TABLE public.pedidos
  ALTER COLUMN data_pedido SET NOT NULL;

COMMENT ON COLUMN public.pedidos.data_pedido IS
  'db/89: data COMERCIAL do Pedido, declarada e corrigivel pelo operador. Default = data local America/Sao_Paulo. NAO e o instante tecnico de criacao: criado_em continua sendo o timestamp imutavel e NAO pode ser usado como data comercial.';

-- ============================================================
-- 2. public.pedidos.numero — positividade
-- ============================================================
DO $numero_chk$
BEGIN
  IF NOT EXISTS (
    SELECT 1
      FROM pg_constraint
     WHERE conrelid = 'public.pedidos'::regclass
       AND conname  = 'pedidos_numero_positivo_chk'
  ) THEN
    ALTER TABLE public.pedidos
      ADD CONSTRAINT pedidos_numero_positivo_chk CHECK (numero > 0);
  END IF;
END;
$numero_chk$;

-- ============================================================
-- 3. Imutabilidade de public.pedidos.numero
--    Nenhum caminho de UI nem DML direto pode renumerar um Pedido ja criado.
--    Update de mesmo valor e aceito (o gatilho nem dispara).
--    Sem bypass geral: nao existe GUC de escape para este guard.
-- ============================================================
CREATE OR REPLACE FUNCTION public.pedidos_numero_immutability_guard_fn()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  -- Defesa em profundidade: o WHEN do gatilho ja restringe a mudanca real,
  -- e esta checagem mantem a funcao correta se for reusada sem ele.
  IF NEW.numero IS DISTINCT FROM OLD.numero THEN
    RAISE EXCEPTION
      'pedidos.numero e imutavel apos a criacao (pedido %: % -> %)',
      OLD.id, OLD.numero, NEW.numero
      USING ERRCODE = '23514';
  END IF;
  RETURN NEW;
END;
$$;

COMMENT ON FUNCTION public.pedidos_numero_immutability_guard_fn() IS
  'db/89: recusa qualquer UPDATE que altere pedidos.numero. Update de mesmo valor e aceito. Sem bypass.';

REVOKE EXECUTE ON FUNCTION public.pedidos_numero_immutability_guard_fn() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.pedidos_numero_immutability_guard_fn() FROM anon;

DROP TRIGGER IF EXISTS pedidos_numero_immutability_guard ON public.pedidos;
CREATE TRIGGER pedidos_numero_immutability_guard
  BEFORE UPDATE ON public.pedidos
  FOR EACH ROW
  WHEN (NEW.numero IS DISTINCT FROM OLD.numero)
  EXECUTE FUNCTION public.pedidos_numero_immutability_guard_fn();

-- ============================================================
-- 4. Sincronizacao da sequencia de identidade
--    Um numero explicito ALTO avanca a sequencia; um numero explicito BAIXO
--    nao a move. A sequencia nunca retrocede. Lacunas sao toleradas.
-- ============================================================
CREATE OR REPLACE FUNCTION public.pedidos_numero_sequence_sync_fn()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_seq  regclass;
  v_last BIGINT;
BEGIN
  IF NEW.numero IS NULL THEN
    RETURN NULL;
  END IF;

  v_seq := pg_get_serial_sequence('public.pedidos', 'numero')::regclass;
  IF v_seq IS NULL THEN
    RETURN NULL;
  END IF;

  -- Serializa os sincronizadores entre si. Escopo de transacao, tomado ANTES
  -- de qualquer leitura da sequencia, e este gatilho nao trava linha alguma:
  -- e uma FOLHA na ordem global de locks de db/88.
  PERFORM pg_advisory_xact_lock(hashtext('public.pedidos_numero_seq_sync')::BIGINT);

  -- pg_sequence_last_value devolve NULL enquanto a sequencia nunca foi usada.
  v_last := pg_sequence_last_value(v_seq);

  -- SOMENTE para frente. Um numero explicito menor que o corrente nao move
  -- a sequencia, entao numeros automaticos ja emitidos nunca sao reemitidos.
  IF v_last IS NULL OR NEW.numero > v_last THEN
    PERFORM setval(v_seq, NEW.numero, true);
  END IF;

  RETURN NULL;
END;
$$;

COMMENT ON FUNCTION public.pedidos_numero_sequence_sync_fn() IS
  'db/89: apos inserir um Pedido, avanca pedidos_numero_seq quando o numero inserido excede o valor corrente da sequencia. Nunca retrocede. Lacunas sao aceitas; numeracao gapless NAO e tentada. UNIQUE(numero) continua sendo o backstop final de concorrencia.';

REVOKE EXECUTE ON FUNCTION public.pedidos_numero_sequence_sync_fn() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.pedidos_numero_sequence_sync_fn() FROM anon;

DROP TRIGGER IF EXISTS pedidos_numero_sequence_sync ON public.pedidos;
CREATE TRIGGER pedidos_numero_sequence_sync
  AFTER INSERT ON public.pedidos
  FOR EACH ROW
  EXECUTE FUNCTION public.pedidos_numero_sequence_sync_fn();

-- ============================================================
-- 5. Reload PostgREST
-- ============================================================
NOTIFY pgrst, 'reload schema';
NOTIFY pgrst, 'reload config';

COMMIT;
